# values-security.yaml
security:
  enabled: true
  namespace: edge-apps
  healthCheckPort: 8080 

edges:
  - name: edge-a
    pmus:
      - label: "PMU-A1"
        ip: "172.17.1.49"
        port: 1410
        pdc_id: 10
      - label: "PMU-A2"
        ip: "172.17.1.49"
        port: 1411
        pdc_id: 11
      # - label: "PMU-A3"
      #   ip: "172.17.1.49"
      #   port: 1412
      #   pdc_id: 12
  - name: edge-b
    pmus:
      - label: "PMU-B1"
        ip: "192.168.177.140"
        port: 1410
        pdc_id: 20
      # - label: "PMU-B2"
      #   ip: "192.168.177.140"
      #   port: 1411
      #   pdc_id: 21
  - name: edge-c
    pmus: 
      - label: "PMU-C1"
        ip: "172.20.10.6"
        port: 1410
        pdc_id: 20
      - label: "PMU-C2"
        ip: "172.20.10.6"
        port: 1411
        pdc_id: 21
  - name: edge-d
    pmus: 
      - label: "PMU-D1"
        ip: "172.18.1.94"
        port: 1410
        pdc_id: 20

maintenance_mode: 
  edge-a: false
  edge-b: false
