# values-security.yaml
security:
  enabled: false
  namespace: edge-apps
  healthCheckPort: 8080 

edges:
  - name: edge-a
    pmus:
      - ip: "172.17.1.49"
        port: 1410
      - ip: "172.17.1.49"
        port: 1411
      - ip: "172.17.1.49"
        port: 1412
  - name: edge-b
    pmus:
      - ip: "192.168.177.140"
        port: 1410
      - ip: "192.168.177.140"
        port: 1411

maintenance_mode: 
  edge-a: false
  edge-b: false

cloud_db_cluster_name: "timescaledb-cloud"