{{- range .Values.edges }}
{{- $edgeName := .name }}
{{- if index $.Values.maintenance_mode $edgeName }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: manual-backup-{{ $edgeName }}-{{ now | unixEpoch }}
  namespace: edge-apps
spec:
  cluster:
    name: timescaledb-{{ $edgeName }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb-maintenance-{{ $edgeName }}
  namespace: edge-apps
  labels:
    role: maintenance-db
    edge-origin: {{ $edgeName }}
spec:
  instances: 1
  imageName: {{ $.Values.images.timescaledb | quote }}

  bootstrap:
    recovery:
      source: src-{{ $edgeName }}
      backupID: "20260325T100001"
      {% comment %} recoveryTarget:
        targetTime: "{{ now | dateModify "-30m" | date "2006-01-02 15:04:05" }}" {% endcomment %}

  externalClusters:
    - name: src-{{ $edgeName }}
      barmanObjectStore:
        destinationPath: s3://pmu-backup/{{ $edgeName }}/
        serverName: "timescaledb-{{ $edgeName }}"
        endpointURL: http://minio.minio-system.svc.cluster.local:9000
        s3Credentials:
          accessKeyId:
            name: wal-g-creds
            key: access-key
          secretAccessKey:
            name: wal-g-creds
            key: secret-key
        wal:
          compression: gzip
    
  backup:
    barmanObjectStore:
      destinationPath: s3://pmu-backup/{{ $edgeName }}/maintenance-data/
      serverName: "maintenance-cloud-{{ $edgeName }}"
      endpointURL: http://minio.minio-system.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: wal-g-creds
          key: access-key
        secretAccessKey:
          name: wal-g-creds
          key: secret-key
      wal:
        compression: gzip

  replica:
    enabled: false
    source: src-{{ $edgeName }}

  storage:
    size: 5Gi 
    storageClass: local-path

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - {{ $.Values.cloud_node_name | quote }}

  postgresql:
    parameters: 
      archive_timeout: "300s"
{{- end }}
{{- end }}