{{- range .Values.edges }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-producer-{{ .name }}
  namespace: edge-apps  
spec:
  replicas: 1          
  selector:
    matchLabels:
      app: ems-producer
      edge: {{ .name }}
  template:
    metadata:
      labels:
        app: ems-producer
        edge: {{ .name }}
    spec:
      serviceAccountName: ems-producer-sa
      nodeSelector:
        kubernetes.io/hostname: {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}
      containers:
        - name: producer
          image: plubpo/ems-app:v8.8
          command: ["python", "producer.py"]
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "timescaledb-{{ .name }}-entry"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-{{ .name }}-app
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: timescaledb-{{ .name }}-app
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: timescaledb-{{ .name }}-app
                  key: dbname
            - name: MANUAL_DATA_COUNT
              value: "0"
            - name: DIVIDER_VALUE
              value: "1"
            - name: WORKER_SERVICE_NAME
              value: "ems-worker-service-{{ .name }}"
            - name: NAMESPACE
              value: "edge-apps"
---
apiVersion: v1
kind: Service
metadata:
  name: ems-producer-service-{{ .name }}
  namespace: edge-apps
  labels:
    app: ems-producer
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: metrics
  selector:
    app: ems-producer
{{- end }}