{{- range .Values.edges }}
---
# --- Deployment สำหรับ EMS ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-{{ .name }}
  namespace: edge-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems
      edge: {{ .name }}
  template:
    metadata:
      labels:
        app: ems
        edge: {{ .name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}
      containers:
      - name: ems
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        command: ["python", "{{ $.Values.scripts.ems }}"]
        env:
        - name: SIM_MODE        
          value: "matrix"
        - name: DB_HOST
          value: "timescaledb-{{ .name }}-entry"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: dbname
        resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
{{- end }}