{{- range .Values.edges }}
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ems-{{ .name }}
  namespace: edge-apps
spec:
  rayVersion: '2.9.0'
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      include-dashboard: 'false'
      dashboard-host: '0.0.0.0'
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}
        containers:
        - name: ray-head
          image: "patiphan11/ems:v4"
          command: ["/bin/bash", "-c"]
          args:
            - |
              ray start --head --port=6379 --include-dashboard=false --num-cpus=0 &
              sleep 10;
              python3 /app/ems-blackbox.py
          readinessProbe:
            initialDelaySeconds: 45  
            periodSeconds: 10
            exec: 
              command: ["/bin/bash", "-c", "wget -q -O- http://localhost:6379/healthz"]
          livenessProbe:
            initialDelaySeconds: 90  
            periodSeconds: 15
            exec: 
              command: ["/bin/bash", "-c", "wget -q -O- http://localhost:6379/healthz"]
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 10001
            name: client
          env:
          - name: SIM_MODE        
            value: "loop"
          - name: MANUAL_DATA_COUNT
            value: "1000"
          - name: DIVIDER_VALUE
            value: "1"
          - name: DB_HOST
            value: "timescaledb-{{ .name }}-entry"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: timescaledb-{{ .name }}-app
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: timescaledb-{{ .name }}-app
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: timescaledb-{{ .name }}-app
                key: dbname
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

  workerGroupSpecs:
  - replicas: 1
    minReplicas: 0
    maxReplicas: 10
    groupName: compute-pool
    rayStartParams: {}
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}
        containers:
        - name: ray-worker
          image: "patiphan11/ems:v4"
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "exit 0"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "exit 0"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
{{- end }}