{{- range .Values.edges }}
{{- $edgeName := .name -}}
---
# --- Deployment สำหรับ PDC ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdc-{{ $edgeName }}
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdc
      edge: {{ $edgeName }}
  template:
    metadata:
      labels:
        app: pdc
        edge: {{ $edgeName }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ $edgeName }}
            
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ $.Values.cloud_node_name | quote }}

      containers:
      - name: pdc
        image: "plubpo/pdc-app:v2.3"
        #command: ["python", "{{ $.Values.scripts.pdc }}"]
        env:
        - name: PMU_LIST
          value: |
            [
              {{- range $index, $pmu := .pmus -}}
              {{ if $index }},{{ end }}
              {
                "label": {{ $pmu.label | quote }},
                "service_name": "pmu-{{ $edgeName }}-{{ $pmu.label | lower }}",
                "port": {{ $pmu.port }},
                "pdc_id": {{ $pmu.pdc_id }}
              }
              {{- end }}
            ]
        - name: DB_HOST
          value: "timescaledb-service-{{ .name }}.edge-apps"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "password"
        - name: DB_NAME
          value: "postgres"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: pdc-service-{{ .name }}
  namespace: edge-apps
  annotations:
    prometheus.io/scrape: "true"    
    prometheus.io/port: "5001"     
    prometheus.io/path: "/metrics" 
  labels:
    app: pdc
spec:
  ports:
    - port: 5001
      targetPort: 5001
      name: metrics
  selector:
    app: pdc
    edge: {{ $edgeName }}
{{ end }}
