{{- range .Values.edges }}
---
# --- Deployment สำหรับ PDC ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdc-{{ .name }}
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdc
      edge: {{ .name }}
  template:
    metadata:
      labels:
        app: pdc
        edge: {{ .name }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: [ "{{ .name }}" ]
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: [ "{{ $.Values.cloud_node_name }}" ]
      containers:
      - name: pdc
        image: "patiphan11/pdc-onepmu:v1"
        #command: ["python", "{{ $.Values.scripts.pdc }}"]
        env:
        - name: DB_HOST
          value: "timescaledb-{{ .name }}-rw"
        - name: PMU_IP
          value: "pmu-service-{{ .name }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: timescaledb-{{ .name }}-app
              key: dbname
{{- end }}
