{{- range $edge := .Values.edges }}
{{- range $pmu := $edge.pmus }}
---
apiVersion: v1
kind: Service
metadata:
  name: pmu-{{ $edge.name }}-{{ $pmu.label | lower }}
  namespace: edge-apps
spec:
  ports:
    - protocol: TCP
      port: {{ $pmu.port }}
      targetPort: {{ $pmu.port }}

---
apiVersion: v1
kind: Endpoints
metadata:
  name: pmu-{{ $edge.name }}-{{ $pmu.label | lower }}
  namespace: edge-apps
subsets:
  - addresses:
      - ip: {{ $pmu.ip | quote }} 
    ports:
      - port: {{ $pmu.port }}
{{- end }}
{{- end }}