{{- range .Values.edges }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb-{{ .name }}
  namespace: edge-apps
spec:
  instances: 1
  imageName: {{ $.Values.images.timescaledb | quote }}

  bootstrap:
    initdb:
      database: app
      owner: app
      postInitSQL:
        - |
          CREATE TABLE IF NOT EXISTS pmu_measurements (
              time TIMESTAMPTZ NOT NULL,
              frequency DOUBLE PRECISION,
              magnitude DOUBLE PRECISION, angle DOUBLE PRECISION,
              mag_b DOUBLE PRECISION, ang_b DOUBLE PRECISION,
              mag_c DOUBLE PRECISION, ang_c DOUBLE PRECISION
          );
          -- เพิ่ม Column เผื่อไว้กรณีต้องการความชัวร์
          ALTER TABLE pmu_measurements ADD COLUMN IF NOT EXISTS mag_b DOUBLE PRECISION;
          ALTER TABLE pmu_measurements ADD COLUMN IF NOT EXISTS ang_b DOUBLE PRECISION;
          ALTER TABLE pmu_measurements ADD COLUMN IF NOT EXISTS mag_c DOUBLE PRECISION;
          ALTER TABLE pmu_measurements ADD COLUMN IF NOT EXISTS ang_c DOUBLE PRECISION;
          
          -- หมายเหตุ: ถ้าใช้ Image Plain Postgres บรรทัด Hypertable ด้านล่างจะ Error 
          -- แต่จะไม่ทำให้การสร้าง Table ด้านบนพังเพราะมันรันแยกบรรทัดกันใน postInitSQL
          -- SELECT create_hypertable('pmu_measurements', 'time', if_not_exists => TRUE);

  storage:
    size: 1Gi
    storageClass: local-path

  nodeSelector:
    kubernetes.io/hostname: {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}

  backup:
    barmanObjectStore:
      destinationPath: s3://pmu-backup/{{ .name }}/
      endpointURL: http://minio.minio-system.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: wal-g-creds
          key: access-key
        secretAccessKey:
          name: wal-g-creds
          key: secret-key
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
      retentionPolicy: "1d"

  postgresql:
    parameters: 
      archive_timeout: "300s"

---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-{{ .name }}-rw
  namespace: edge-apps
spec:
  selector:
    {{- if index $.Values.maintenance_mode .name }}
    cnpg.io/cluster: timescaledb-cloud
    {{- else }}
    cnpg.io/cluster: timescaledb-{{ .name }}
    {{- end }}
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}