{{- range .Values.edges }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb-{{ .name }}
  namespace: edge-apps
spec:
  instances: 1
  imageName: {{ $.Values.images.timescaledb | quote }}

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 1Gi
    storageClass: local-path

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - {{ if index $.Values.maintenance_mode .name }}{{ $.Values.cloud_node_name | quote }}{{ else }}{{ .name | quote }}{{ end }}

  backup:
    barmanObjectStore:
      destinationPath: s3://pmu-backup/{{ .name }}/
      endpointURL: http://minio.minio-system.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: wal-g-creds
          key: access-key
        secretAccessKey:
          name: wal-g-creds
          key: secret-key
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
    
  externalClusters:
    - name: maintenance-source
      barmanObjectStore:
        destinationPath: s3://pmu-backup/{{ .name }}/maintenance-data/
        serverName: "maintenance-cloud-{{ .name }}"
        endpointURL: http://minio.minio-system.svc.cluster.local:9000
        s3Credentials:
          accessKeyId:
            name: wal-g-creds
            key: access-key
          secretAccessKey:
            name: wal-g-creds
            key: secret-key
          
  postgresql:
    parameters: 
      archive_timeout: "300s"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: timescaledb-{{ .name }}-daily-backup
  namespace: edge-apps
spec:
  schedule: "0 0 * * *" 
  backupOwnerReference: self
  cluster:
    name: timescaledb-{{ .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-{{ .name }}-entry
  namespace: edge-apps
spec:
  selector:
    {{- if index $.Values.maintenance_mode .name }}
    cnpg.io/cluster: timescaledb-cloud
    {{- else }}
    cnpg.io/cluster: timescaledb-{{ .name }}
    {{- end }}
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}