{{- range .Values.edges }}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: pdc-policy-{{ .name }}
  namespace: {{ $.Values.security.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: pdc
      edge: {{ .name | quote }}
  
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: {{ $.Values.security.healthCheckPort | quote }}
              protocol: TCP
    
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": monitoring
            app: prometheus
      toPorts:
        - ports:
            - port: "5001" 
              protocol: TCP

  egress:
    - toCIDR:
        {{- range .pmus }}
        - {{ .ip }}/32
        {{- end }}
      toPorts:
        - ports:
          {{- range .pmus }}
          - port: {{ .port | quote }}
            protocol: TCP
          {{- end }}

    - toEndpoints:
        - matchLabels:
            {{- if index $.Values.maintenance_mode .name }}
            cnpg.io/cluster: {{ $.Values.cloud_db_cluster_name }}
            {{- else }}
            cnpg.io/cluster: timescaledb-{{ .name }}
            {{- end }}
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
{{- end }}