apiVersion: v1
kind: Namespace
metadata:
  name: minio-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.15
    helm:
      values: |
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"

        rootUser: "minioadmin"
        rootPassword: "minioadmin" 

        persistence:
          enabled: true
          size: 10Gi 

        consoleService:
          type: ClusterIP

        mode: standalone
        replicas: 1

        resources:
          requests:
            memory: "512Mi" 
            cpu: "250m"
          limits:
            memory: "2Gi"   

  destination:
    server: https://kubernetes.default.svc
    namespace: minio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    createNamespace: true
