apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wal-g-creds
  namespace: edge-apps
spec:
  refreshInterval: 1h 
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: wal-g-creds 
  data:
    - secretKey: access-key
      remoteRef:
        key: minio 
        property: accessKey
    - secretKey: secret-key
      remoteRef:
        key: minio
        property: secretKey