apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-ingestor-config
  namespace: cloud-db
data:
  PROM_URL: "http://prometheus-stack-server.monitoring:80"
  POLL_INTERVAL: "15"

  DB_HOST: "systemdb.cloud-db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "autoscale-db"
  DB_USER: "admin"
  DB_PASS: "admin123"