# values.yaml
edges:
  # - name: edge-a
  #   pmu_ip: "192.168.177.140" 
  - name: edge-b
    pmu_ip: "192.168.177.140" 
  # - name: edge-c
  #   pmu_ip: "192.168.177.140" 

image:
  repository: "ghcr.io/patiphan-pluem/iiot-project"
  tag: "v11"
  pullPolicy: "IfNotPresent"

images:
  timescaledb: "timescale/timescaledb:2.17.2-pg14"  

scripts:
  pdc: "TinyPDC.py" 
  ems: "ems_simulator.py"

cloud_node_name: "cloud-node"