# values.yaml
edges:
  - name: edge-a
    pmus:
      - label: "PMU-A1"
        ip: "172.17.1.49"
        port: 1410
        pdc_id: 10
      # - label: "PMU-A2"
      #   ip: "172.17.1.49"
      #   port: 1411
      #   pdc_id: 11
  - name: edge-b
    pmus:
      - label: "PMU-B1"
        ip: "192.168.177.140"
        port: 1410
        pdc_id: 20
      - label: "PMU-B2"
        ip: "192.168.177.140"
        port: 1411
        pdc_id: 21

image:
  repository: "ghcr.io/patiphan-pluem/iiot-project"
  tag: "v14"
  pullPolicy: "IfNotPresent"

images:
  timescaledb: "ghcr.io/cloudnative-pg/postgresql:16.4"  

scripts:
  pdc: "TinyPDC2.py" 
  ems: "ems_simulator.py"

cloud_node_name: "cloud-node"

maintenance_mode: 
  edge-a: false
  edge-b: false
  # edge-c: false
  # edge-d: false
  