name: Build and Push PMU and PDC

on:
  push:
    branches: [ "main" , "feat/iiot-setting", "feat/database-test", "feat/security-test"]
    # paths:
    #   - 'IIoT-devices/**'
    #   - 'system-apps/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- ส่วนของ PDC for 1 PMU ---
      - name: Build and push PDC
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu      
          file: ./IIoT-devices/onepmu/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pdc-onepmu:v4

      # --- ส่วนของ PDC for many PMUs ---
      - name: Build and push PDC
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices    
          file: ./IIoT-devices/Dockerfile    
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pdc-pmus:v1

      # --- ส่วนของ PMU baseline ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline          
          file: ./IIoT-devices/onepmu/PMU/Baseline/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-baseline:v2

      # --- ส่วนของ PMU onoff ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/OnOff          
          file: ./IIoT-devices/onepmu/PMU/OnOff/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-onoff:v1


      # --- ส่วนของ PMU Ramp ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Ramp         
          file: ./IIoT-devices/onepmu/PMU/Ramp/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-ramp:v1
      
      # --- ส่วนของ 2 PMU OnOff4State ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/twopmu/OnOff4State       
          file: ./IIoT-devices/twopmu/OnOff4State/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-onoff4state:v1

      # --- ส่วนของ 2 PMU Spike ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/twopmu/Spike      
          file: ./IIoT-devices/twopmu/Spike/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-spike:v1

      # --- ส่วนของ 3 PMU Spike ---
      - name: Build and push PMU
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/threepmu/Spike      
          file: ./IIoT-devices/threepmu/Spike/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu-spike-3pmus:v2

      # --- ส่วนของ Ingestor ---
      - name: Build and push Ingestor
        uses: docker/build-push-action@v5
        with:
          context: ./system-apps/Ingestor    
          file: ./system-apps/Ingestor/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ingestor:v1
      