name: Build and Push baseline PMU

on:
  push:
    branches: [ "main" , "feat/ML-testing-b"]
    paths:
      - 'IIoT-devices/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU10      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU10/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu10:v1

    
      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU12      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU12/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu12:v1

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU15      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU15/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu15:v1

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU20     
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU20/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu20:v1

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU30      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU30/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu30:v1
      
      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU50      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU50/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu50:v1

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMU60      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMU60/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmu60:v1

      - name: Build and push PMU baseline
        uses: docker/build-push-action@v5
        with:
          context: ./IIoT-devices/onepmu/PMU/Baseline2/PMUX      
          file: ./IIoT-devices/onepmu/PMU/Baseline2/PMUX/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmux:v1