name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ] 
    paths:
      - 'service-apps/edge-apps/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: patiphan-pluem/iiot-project

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./service-apps/edge-apps/
          file: ./service-apps/edge-apps/Dockerfile
          push: true
          tags: |
            ghcr.io/patiphan-pluem/iiot-project:v12
            ghcr.io/patiphan-pluem/iiot-project:${{ github.sha }}